services:
  - type: web
    name: email-helper-backend
    env: node
    region: frankfurt
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ALLOW_ALL_CORS_DEV
        value: 0
    healthCheckPath: /api/health
